const words = [
  { spanish: 'familia', english: 'family' },
  { spanish: 'no', english: 'no' },
  { spanish: 'es', english: 'is' },
  { spanish: 'muy', english: 'very' },
  { spanish: 'grande', english: 'big' },
  { spanish: 'somos', english: 'we are' },
  { spanish: 'solo', english: 'only' },
  { spanish: 'cuatro', english: 'four' },
  { spanish: 'personas', english: 'people' },
  { spanish: 'padre', english: 'father' },
  { spanish: 'madre', english: 'mother' },
  { spanish: 'hermana', english: 'sister' },
  { spanish: 'yo', english: 'I' },
  { spanish: 'también', english: 'also' },
  { spanish: 'tenemos', english: 'we have' },
  { spanish: 'perro', english: 'dog' },
  { spanish: 'soy', english: 'I am' },
  { spanish: 'mayor', english: 'older' },
  { spanish: 'que', english: 'than' },
  { spanish: 'pero', english: 'but' },
  { spanish: 'ella', english: 'she' },
  { spanish: 'es', english: 'is' },
  { spanish: 'más', english: 'more' },
  { spanish: 'alta', english: 'tall (fem.)' },
  { spanish: 'tengo', english: 'I have' },
  { spanish: 'doce', english: 'twelve' },
  { spanish: 'años', english: 'years' },
  { spanish: 'y', english: 'and' },
  { spanish: 'once', english: 'eleven' },
  { spanish: 'mis', english: 'my (plural)' },
  { spanish: 'padres', english: 'parents' },
  { spanish: 'se llaman', english: 'are named' },
  { spanish: 'Javier', english: 'Javier (name)' },
  { spanish: 'María', english: 'María (name)' },
  { spanish: 'Sara', english: 'Sara (name)' },
  { spanish: 'Luis', english: 'Luis (name)' },
  { spanish: 'vivimos', english: 'we live' },
  { spanish: 'todos', english: 'all' },
  { spanish: 'juntos', english: 'together' },
  { spanish: 'casa', english: 'house' },
  { spanish: 'bonita', english: 'pretty, nice' },
  { spanish: 'banquero', english: 'banker' },
  { spanish: 'ama de casa', english: 'housewife' },
  { spanish: 'por la mañana', english: 'in the morning' },
  { spanish: 'desayunamos', english: 'we have breakfast' },
  { spanish: 'cocina', english: 'kitchen' },
  { spanish: 'me gusta', english: 'I like' },
  { spanish: 'además', english: 'besides' },
  { spanish: 'siempre', english: 'always' },
  { spanish: 'tengo hambre', english: 'I am hungry' },
  { spanish: 'después', english: 'after' },
  { spanish: 'colegio', english: 'school' },
  { spanish: 'prepara', english: 'prepares' },
  { spanish: 'comida', english: 'meal, food' },
  { spanish: 'deliciosa', english: 'delicious' },
  { spanish: 'por la tarde', english: 'in the afternoon' },
  { spanish: 'queda', english: 'meets up' },
  { spanish: 'con', english: 'with' },
  { spanish: 'sus', english: 'her (plural)' },
  { spanish: 'amigas', english: 'friends (fem.)' },
  { spanish: 'padre', english: 'father' },
  { spanish: 'juega', english: 'plays' },
  { spanish: 'al tenis', english: 'tennis' },
  { spanish: 'hacemos', english: 'we do' },
  { spanish: 'los deberes', english: 'homework' },
  { spanish: 'vemos', english: 'we watch' },
  { spanish: 'la televisión', english: 'television' },
  { spanish: 'los viernes', english: 'Fridays' },
  { spanish: 'de compras', english: 'shopping' },
  { spanish: 'alto', english: 'tall (masc.)' },
  { spanish: 'rubio', english: 'blonde (masc.)' },
  { spanish: 'morena', english: 'brunette (fem.)' },
  { spanish: 'delgada', english: 'slim (fem.)' },
  { spanish: 'le gusta', english: 'she likes' },
  { spanish: 'parque', english: 'park' },
  { spanish: 'me divierto', english: 'I have fun' },
  { spanish: 'mucho más', english: 'much more' },
  { spanish: 'jugando', english: 'playing' },
  { spanish: 'videojuegos', english: 'video games' },
  { spanish: 'en casa', english: 'at home' }
];
