// words.js

const words = [
  // ==========================
  // 1) ORIGINAL 100 WORDS
  // ==========================
  { spanish: 'el',      english: 'the (masc.)' },
  { spanish: 'la',      english: 'the (fem.)' },
  { spanish: 'de',      english: 'of, from' },
  { spanish: 'que',     english: 'that, which' },
  { spanish: 'y',       english: 'and' },
  { spanish: 'a',       english: 'to, at' },
  { spanish: 'en',      english: 'in, on' },
  { spanish: 'un',      english: 'a, an (masc.)' },
  { spanish: 'ser',     english: 'to be (essential)' },
  { spanish: 'se',      english: 'oneself; pronoun' },
  { spanish: 'no',      english: 'no' },
  { spanish: 'haber',   english: 'to have (aux.)' },
  { spanish: 'por',     english: 'by, for, through' },
  { spanish: 'con',     english: 'with' },
  { spanish: 'su',      english: 'his, her, its, their' },
  { spanish: 'para',    english: 'for, in order to' },
  { spanish: 'como',    english: 'like, as' },
  { spanish: 'estar',   english: 'to be (state)' },
  { spanish: 'tener',   english: 'to have' },
  { spanish: 'le',      english: 'to him/her (IO pronoun)' },
  { spanish: 'lo',      english: 'it, him (DO pronoun)' },
  { spanish: 'todo',    english: 'all, everything' },
  { spanish: 'pero',    english: 'but' },
  { spanish: 'más',     english: 'more' },
  { spanish: 'hacer',   english: 'to do, to make' },
  { spanish: 'o',       english: 'or' },
  { spanish: 'poder',   english: 'to be able to, can' },
  { spanish: 'decir',   english: 'to say' },
  { spanish: 'este',    english: 'this (masc.)' },
  { spanish: 'ir',      english: 'to go' },
  { spanish: 'otro',    english: 'other, another' },
  { spanish: 'ese',     english: 'that (masc.)' },
  { spanish: 'sí',      english: 'yes' },
  { spanish: 'me',      english: 'me, to me' },
  { spanish: 'ya',      english: 'already, now' },
  // UNIFIED here: changed from "to see" to "to see, to watch"
  { spanish: 'ver',     english: 'to see, to watch' },
  { spanish: 'porque',  english: 'because' },
  { spanish: 'dar',     english: 'to give' },
  { spanish: 'cuando',  english: 'when' },
  { spanish: 'él',      english: 'he, him' },
  { spanish: 'muy',     english: 'very' },
  { spanish: 'sin',     english: 'without' },
  { spanish: 'vez',     english: 'time (occurrence)' },
  { spanish: 'mucho',   english: 'much, a lot' },
  { spanish: 'saber',   english: 'to know (facts)' },
  { spanish: 'qué',     english: 'what' },
  { spanish: 'sobre',   english: 'about, on, over' },
  { spanish: 'mi',      english: 'my' },
  { spanish: 'alguno',  english: 'some, any' },
  { spanish: 'mismo',   english: 'same' },
  { spanish: 'yo',      english: 'I' },
  { spanish: 'también', english: 'also' },
  { spanish: 'hasta',   english: 'until, up to' },
  { spanish: 'año',     english: 'year' },
  { spanish: 'dos',     english: 'two' },
  { spanish: 'querer',  english: 'to want, to love' },
  { spanish: 'entre',   english: 'between, among' },
  { spanish: 'así',     english: 'like this, thus' },
  { spanish: 'primero', english: 'first' },
  { spanish: 'desde',   english: 'from, since' },
  { spanish: 'grande',  english: 'big, large' },
  { spanish: 'eso',     english: 'that (neuter)' },
  { spanish: 'ni',      english: 'neither, nor' },
  { spanish: 'nos',     english: 'us, to us' },
  { spanish: 'llegar',  english: 'to arrive' },
  { spanish: 'pasar',   english: 'to pass, happen' },
  { spanish: 'tiempo',  english: 'time, weather' },
  { spanish: 'ella',    english: 'she, her' },
  { spanish: 'día',     english: 'day' },
  { spanish: 'uno',     english: 'one' },
  { spanish: 'bien',    english: 'well, good' },
  { spanish: 'poco',    english: 'little, few' },
  { spanish: 'deber',   english: 'should, must; to owe' },
  { spanish: 'entonces',english: 'then' },
  { spanish: 'poner',   english: 'to put' },
  { spanish: 'cosa',    english: 'thing' },
  { spanish: 'tanto',   english: 'so much' },
  { spanish: 'hombre',  english: 'man' },
  { spanish: 'parecer', english: 'to seem, appear' },
  { spanish: 'nuestro', english: 'our' },
  { spanish: 'tan',     english: 'so (degree)' },
  { spanish: 'donde',   english: 'where' },
  { spanish: 'ahora',   english: 'now' },
  { spanish: 'parte',   english: 'part' },
  { spanish: 'después', english: 'after' },
  { spanish: 'vida',    english: 'life' },
  { spanish: 'quedar',  english: 'to remain, stay' },
  { spanish: 'siempre', english: 'always' },
  { spanish: 'creer',   english: 'to believe' },
  { spanish: 'hablar',  english: 'to speak' },
  { spanish: 'llevar',  english: 'to carry, wear' },
  { spanish: 'dejar',   english: 'to leave, let' },
  { spanish: 'nada',    english: 'nothing' },
  { spanish: 'cada',    english: 'each, every' },
  { spanish: 'seguir',  english: 'to follow' },
  { spanish: 'menos',   english: 'less' },
  { spanish: 'nuevo',   english: 'new' },
  { spanish: 'encontrar', english: 'to find' },
  { spanish: 'algo',    english: 'something' },
  { spanish: 'solo',    english: 'only, alone' },

  // ======================================================
  // 2) UNIQUE WORDS FROM THE PASSAGE (EXCLUDING DUPLICATES)
  // ======================================================
  { spanish: 'abajo',       english: 'downstairs, below' },
  { spanish: 'además',      english: 'moreover, besides' },
  { spanish: 'alhambra',    english: 'Alhambra (monument in Granada)' },
  { spanish: 'amigos',      english: 'friends' },
  { spanish: 'ancha',       english: 'wide (fem.)' },
  { spanish: 'árboles',     english: 'trees' },
  { spanish: 'arriba',      english: 'upstairs, above' },
  { spanish: 'calle',       english: 'street' },
  { spanish: 'carnicería',  english: 'butcher shop' },
  { spanish: 'casa',        english: 'house' },
  { spanish: 'cerca',       english: 'near' },
  { spanish: 'cenar',       english: 'to have dinner' },
  { spanish: 'ciudad',      english: 'city' },
  { spanish: 'cocina',      english: 'kitchen' },
  { spanish: 'comedor',     english: 'dining room' },
  { spanish: 'compra',      english: 'shopping' },
  { spanish: 'comida',      english: 'food' },
  { spanish: 'cortinas',    english: 'curtains' },
  { spanish: 'despacho',    english: 'office, study' },
  { spanish: 'dormitorios', english: 'bedrooms' },
  { spanish: 'famosos',     english: 'famous (pl. masc.)' },
  { spanish: 'fútbol',      english: 'soccer/football' },
  { spanish: 'gazpacho',    english: 'gazpacho (cold soup)' },
  { spanish: 'granada',     english: 'Granada (city in Spain)' },
  { spanish: 'gustar',      english: 'to like (used as "me gusta")' },
  { spanish: 'hay',         english: 'there is, there are' },
  { spanish: 'importantes', english: 'important (pl.)' },
  { spanish: 'invitar',     english: 'to invite' },
  { spanish: 'mesa',        english: 'table' },
  { spanish: 'mis',         english: 'my (plural)' },
  { spanish: 'monumentos',  english: 'monuments' },
  { spanish: 'muchas',      english: 'many (fem.)' },
  { spanish: 'nueva',       english: 'new (fem.)' },
  { spanish: 'panadería',   english: 'bakery' },
  { spanish: 'pequeña',     english: 'small (fem.)' },
  { spanish: 'pescadería',  english: 'fishmonger' },
  { spanish: 'piso',        english: 'floor, apartment' },
  { spanish: 'piscina',     english: 'swimming pool' },
  { spanish: 'puedo',       english: 'I can' },
  { spanish: 'rebujito',    english: 'Rebujito (Andalusian cocktail)' },
  { spanish: 'salmorejo',   english: 'Salmorejo (Andalusian cold soup)' },
  { spanish: 'salón',       english: 'living room' },
  { spanish: 'seis',        english: 'six' },
  { spanish: 'sillas',      english: 'chairs' },
  { spanish: 'sol',         english: 'sun' },
  { spanish: 'sofás',       english: 'sofas' },
  { spanish: 'son',         english: 'they are' },
  { spanish: 'televisión',  english: 'television' },
  { spanish: 'terraza',     english: 'terrace' },
  { spanish: 'tiendas',     english: 'stores' },
  { spanish: 'tiene',       english: 'has' },
  { spanish: 'tres',        english: 'three' },
  { spanish: 'verano',      english: 'summer' },
  { spanish: 'vivo',        english: 'I live' }
];
